#!/bin/bash

echo "System aktualisieren & isc-dhcp-server installieren..."
apt update
apt install isc-dhcp-server -y

echo "DHCP-Interface auf eth01 setzen..."
echo 'INTERFACESv4="eth01"' > /etc/default/isc-dhcp-server

echo "DHCP-Konfiguration schreiben..."
cat > /etc/dhcp/dhcpd.conf <<EOF
default-lease-time 600;
max-lease-time 7200;

authoritative;
subnet 10.8.0.0 netmask 255.255.255.0 {
    range 10.8.0.10 10.8.0.100;
    option routers 10.8.0.1;
    option domain-name-servers 1.1.1.1, 8.8.8.8;
}
EOF

echo "DHCP-Server aktivieren & starten..."
systemctl restart isc-dhcp-server
systemctl enable isc-dhcp-server

echo "DHCP-Server fertig eingerichtet. Vergibt IPs von 10.8.0.10 bis 10.8.0.100"
