#!/bin/bash

# WireGuard Konfigurationsdatei erstellen
cat <<EOF > /etc/wireguard/wg0.conf
[Interface]
PrivateKey = 
Address = 
DNS =

[Peer]
PublicKey = 
PresharedKey = 
AllowedIPs = 0.0.0.0/1, ::/1
Endpoint = 
EOF

# Berechtigungen für die WireGuard-Konfigurationsdatei setzen
chmod 600 /etc/wireguard/wg0.conf

# WireGuard installieren, falls nicht vorhanden
apt update
apt install -y wireguard

# WireGuard-Client starten
wg-quick up wg0

# Sicherstellen, dass WireGuard beim Systemstart aktiviert wird
systemctl enable wg-quick@wg0

# Route hinzufügen, um den gesamten Traffic über das VPN zu leiten
ip route add 0.0.0.0/1 dev wg0


# Status der Verbindung anzeigen
wg

# Information über die Weboberfläche
echo "Proxmox-Weboberfläche ist nun über das VPN erreichbar. Zugriff unter https:... (oder die zugewiesene VPN-IP)."
